### ISSUE TITLE
Add bias correction option in recruitment

### ISSUE THREAD

**Issue by msupernaw** [nmfs-fish-tools/RMAS#31]
Is it the same calculation for all recruitment functions? Where does it get applied in all the different functions?

**Comment by Bai-Li-NOAA** [comment]
Hello @msupernaw!
### Double Bias corrections in recruitment
- The CalculateRecruitment function in the Population.hpp uses mean-unbiased bias correction by including [-0.5*sigma_r^2](https://github.com/nmfs-fish-tools/RMAS/blob/077ff53ace96a5bcd76a1729249d8e6c57c12627/src/mas/Population.hpp#L1068). In that case, the estimated R0 and h correspond to arithmetic mean curve of recruitment. 
- However, the spawner-recruit models in the Recruitment.hpp have options to use bias correction again by including the [bc flag](https://github.com/nmfs-fish-tools/RMAS/blob/077ff53ace96a5bcd76a1729249d8e6c57c12627/src/mas/Recruitment.hpp#L363). Here the bias correction method is median-unbiased method and the estimated R0 and h correspond to a geometric mean curve of recruitment. If using median-unbiased method, we need to be careful with the position of bc because different models uses bc in different places. 
- Found those through the [recruitment test](https://github.com/nmfs-fish-tools/RMAS/pull/34). I will add more recruitment tests later this week. 
### Potential solutions:
- Only use bias correction in Population.hpp. Recruitment * (-0.5*sigma_r^2) means using bias correction and recruitment * 1 means not using bias correction.
- Add parentheses around (5h-1) in the [return value from Beverton-Holt model](https://github.com/nmfs-fish-tools/RMAS/blob/077ff53ace96a5bcd76a1729249d8e6c57c12627/src/mas/Recruitment.hpp#L297) in the Recruitment.hpp
return ( 4.0 * this->h * mas::exp(this->log_R0) * sb) / (this->SB0[pop_id][area_id]*(1.0 - this->h) + sb * (5.0 * this->h - 1.0));
- It seems that recruitment$sigma_r$value is standard deviation of log recruitment instead of exp(standard deviation of log recruitment). If so, @Bai-Li-NOAA needs to update all the examples in vignettes.
